### ISSUE TITLE
Exception when double-clicking a package cycle hotspot to show it in Usus Package Graph

### ISSUE THREAD

**Issue by davidburkhart** [usus/usus-plugins#49]
org.projectusus.core.util.Defect: org.eclipse.core.commands.ExecutionException: Could not open view
	at org.projectusus.ui.internal.hotspots.pages.HotspotsPage$2.open(HotspotsPage.java:75)
	at org.eclipse.jface.viewers.StructuredViewer$2.run(StructuredViewer.java:853)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:178)
	at org.eclipse.jface.viewers.StructuredViewer.fireOpen(StructuredViewer.java:850)
	at org.eclipse.jface.viewers.StructuredViewer.handleOpen(StructuredViewer.java:1142)
	at org.eclipse.jface.viewers.StructuredViewer$6.handleOpen(StructuredViewer.java:1249)
	at org.eclipse.jface.util.OpenStrategy.fireOpenEvent(OpenStrategy.java:278)
	at org.eclipse.jface.util.OpenStrategy.access$2(OpenStrategy.java:272)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:313)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:382)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:236)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
Caused by: org.eclipse.core.commands.ExecutionException: Could not open view
	at org.projectusus.ui.dependencygraph.handlers.DependencyGraphViewFilterer.showView(DependencyGraphViewFilterer.java:39)
	at org.projectusus.ui.dependencygraph.handlers.DependencyGraphViewFilterer.activateView(DependencyGraphViewFilterer.java:24)
	at org.projectusus.ui.dependencygraph.handlers.DependencyGraphViewFilterer.applyFilterToView(DependencyGraphViewFilterer.java:18)
	at org.projectusus.ui.dependencygraph.handlers.OpenHotspotInPackageGraph.open(OpenHotspotInPackageGraph.java:30)
	at org.projectusus.ui.internal.hotspots.commands.AbstractOpenHotspotHandler.execute(AbstractOpenHotspotHandler.java:22)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:247)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:229)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:149)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:499)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:508)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:343)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:330)
	at org.projectusus.ui.internal.hotspots.pages.HotspotsPage$2.open(HotspotsPage.java:71)
	... 37 more
Caused by: org.eclipse.ui.PartInitException: Could not create view: org.projectusus.ui.dependencygraph.views.PackageGraphView
	at org.eclipse.ui.internal.WorkbenchPage.busyShowView(WorkbenchPage.java:1261)
	at org.eclipse.ui.internal.WorkbenchPage$13.run(WorkbenchPage.java:4144)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchPage.showView(WorkbenchPage.java:4140)
	at org.eclipse.ui.internal.WorkbenchPage.showView(WorkbenchPage.java:4120)
	at org.projectusus.ui.dependencygraph.handlers.DependencyGraphViewFilterer.showView(DependencyGraphViewFilterer.java:37)
	... 58 more

**Comment by davidburkhart** [comment]
Happened at Project Usus 0.7.6.201501311339

**Comment by davidburkhart** [comment]
Might be fixed by https://github.com/marcphilipp/usus-plugins/commit/26b6ccd1abe81311fb37c287c42b580e6abd8852 already? Is there a release containing this fix?

**Comment by marcphilipp** [comment]
I broke it and fixed it in the mentioned commit. 

I'll release it this weekend. There's a highly unofficial pre-release at https://github.com/marcphilipp/usus-plugins/releases/tag/v0.7.7

**Comment by davidburkhart** [comment]
OK, no problem. It's not a show stopper for me and I am not in a rush ;) As long as the problem is fixed and a release will be built in the near future thats fine for me. Thanks a lot!

**Comment by marcphilipp** [comment]
FYI [Usus 0.7.7 is released](https://github.com/usus/usus-plugins/releases/tag/v0.7.7).
